name: Release
on: [push]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: install pkg
        run: npm install -D pkg

      - name: build
        run: npm run build-${{ matrix.os }}
      - name: add to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/cithak*
          draft: true
          tag_name: v${{ env.GITHUB_SHA }}
