name: Release
on: workflow_dispatch

jobs:
  bundle-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run: npm ci
      - name: bundle javascript files
        run: npm run build

      - name: publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: upload bundled javascript file
        uses: actions/upload-artifact@v2
        with:
          name: cithak-bundle
          path: build/file/cithak.js
          retention-days: 1

  build-executable:
    needs: ['bundle-javascript-file']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: download javascript bundle file
        uses: actions/download-artifact@v2
        with:
          name: cithak-bundle
          path: build/file/

      - name: install dependencies
        run: npm ci
      - name: install pkg
        run: npm install -D pkg
      - name: install resourcehacker
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm install -D node-resourcehacker

      - name: build executable
        run: npm run build-${{ matrix.os }}
      - name: change executable icon
        if: ${{ matrix.os == 'windows-latest' }}
        run: node scripts/setIcon.js

      - name: add to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/cithak*
          draft: true
          tag_name: release-${{ github.sha }}
